# Generated by Django 4.0.2 on 2022-04-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='subTotal',
            new_name='sub_Total',
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
