# Generated by Django 4.0.2 on 2022-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_subtotal_purchasehistory_sub_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsDetails',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
            ],
        ),
    ]
