# Generated by Django 4.0.2 on 2022-04-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_coinsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='coin_id',
            field=models.CharField(default='na', max_length=50),
        ),
    ]
